[tool.poetry]
name = "leetcode"
version = "0.1.0"
description = ""
authors = ["Ken HKS <kenhks014@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.10.5"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pytest = "^7.1.2"
pytest-sugar = "^0.9.4"
isort = "^5.10.1"
flake8 = "^4.0.1"
pyproject-flake8 = "^0.0.1-alpha.4"

[tool.pytest.ini_options]
minversion = "7.0"
norecursedirs = [
    ".git",
    ".venv",
]
python_files = "*.py"

[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.flake8]
max-line-length = 120
exclude = ".venv,.git,__pycache__,"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
